main: eu.octanne.mcboyard.McBoyard
name: McBoyard
description: Plugin pour l'émission McBoyard de ObeProd.
author: Octanne
load: STARTUP
version: 1.1
api-version: 1.16
softdepend: [WorldGuard]
commands:
  standkey:
    description: système des stands key.
  excalibur:
    description: système d'excalibur.
  chestfiller:
    description: système de chestfiller.
  coffrefort:
    description: Salle Le Coffre (Fort).
    permission: mcboyard.coffrefort
  credit:
    description: afficher les credits a un joueur.
  resetcounter:
    description: Réinitialiser le compteur de boyard.
    permission: boyardcounter
  chrono:
    description: Lancer un chronomètre, temps en SECONDE.
    permission: chrono
  pchrono:
    description: Lancer un chronomètre, 10min, 5min, 1min.
    permission: chrono
  chronostop:
    description: Arrêter le chronomètre en cours.
    permission: chrono
  clap:
    description: Lancer un clap de 5 secondes.
    permission: clap
  kitcreate:
    description: Ajouter un kit (Avec les items de l'inventaire).
    permission: kit.admin
  kitreload:
    description: Recharge les fichiers de configuration.
    permission: kit.admin
  amsgreload:
    description: Recharge les fichiers de configuration.
  kit:
    description: Ouvrir le menu des kits.
  maitre:
    description: Cacher son pseudo ou celui du joueur précisé.
  staffchat:
    description: Cacher son pseudo ou celui du joueur précisé.
    aliases: [sc]
  music:
    description: Lancer et stopper la music
  boyardpassword:
    description: Modifier le mot de passe de la salle à Boyard.
  mcboyard:
    description: Paramètres du plugin.
    permission: mcboyard
